### PR TITLE
[NIP5-identifiers] Add NIP-05 identifier converter method

### PR DESCRIPTION
**Pull request by snazzybytes**
### Adds NIP-05 identifier bulk converter support (https://github.com/nostr-protocol/nips/blob/master/05.md)

For each NIP5 domain name, fetches nostr.json and converts hex to bech32 npub equivalent.

### Change summary:
- adding new command option `"--nip5"`
- adding flag  `"--nip-stats"` or `"--s"` (using this flag requires already using `"--nip5"` option)
  - flag can be reused for future NIP related key-converting type features
- added clap parser requirements for proper error handling for "--to-hex" and "--kind" or "--nip5"
  - now both depend on "keys" (Vector<String>) and will throw appropriate error for "KEYS required"
- added clap parser "required" input error handling
- added clap's Error type in the final else, in case someone screws up the arguments logic in the future PRs (guarding against bad code)
- added new + updated dependencies
- updated README

### Usage
To convert list of public keys for a given `NIP-05 domain identifier`, you can
```shell
$> key-convertr --nip5 satoshivibes.com
lukeonchain,npub138guayty78ch9k42n3uyz5ch3jcaa3u390647hwq0c83m2lypekq6wk36k
```
- or you can do multiple domains at once
```shell
$> key-convertr --nip5 satoshivibes.com,nostrplebs.com,strike.me
jack,npub1cn4t4cd78nm900qc2hhqte5aa8c9njm6qkfzw95tszufwcwtcnsq7g3vle
lukeonchain,npub138guayty78ch9k42n3uyz5ch3jcaa3u390647hwq0c83m2lypekq6wk36k
zwartwitzwaan,npub1t4n7gac8dznpnl8wk46arq2k0vnz3f7cwfvvtre2rv7n9kw9a4cstkm262
zyl,npub16zmhar4qrw4hja9uxeu7ms0pxkwft6459klg7w6xfpvqnsgaha2q6kdtav
zzar,npub1egways3vh9y8fstxdjw8ddukrwaw5sexxfjr773de82d90antkussd6l5z
...
...
...
```
- you can also enable NIP5 related stats via "--nip-stats" or "-s";
    - this prints out summary stats in this format: `domain=SomeName.com|count=21`
    - this output could then be parsed (if needed) by other dev tools/libraries
```shell
$> key-convertr --nip5 strike.me --nip-stats
Zaxounette,npub13w02l37gkjwv90lnklfet5653jj0p5ueu976v3dpda5afvxgw3uslcqdnv
cory,npub1dpca3hcdgfdzkplvmsc28dfllth3fkddy4elc92zd9xk2j5njmqsxraun7
ivan,npub10djxr5pvdu97rjkde7tgcsjxzpdzmdguwacfjwlchvj7t88dl7nsdl54nf
jack,npub1cn4t4cd78nm900qc2hhqte5aa8c9njm6qkfzw95tszufwcwtcnsq7g3vle
jespada,npub1747ceatm52f6wexdxre5v88zrv9rsjw9cq6nxwg6zp6yzfsz7lysxd4uzf
manuela,npub1w0s7l9ek32zry7ecn6n0gw4ucg8krzmu9sp3fmhuggjftsqsm3lqns60a6
marfusios,npub1dd668dyr9un9nzf9fjjkpdcqmge584c86gceu7j97nsp4lj2pscs0xk075
matt,npub10p2acl6yd40zu7uu95y496wetwpvepxy4vr9dj74g790d7plht8q73wjkx
mattyp,npub1y7thlx9gxmv57zq3gy7k8z0yxczqf0ngsvdh6m0cgpt4c8qug5wscm350a
mrfelton,npub13zrk607qzmzve7nlmalnl0suealcqt8nxucmhvasgywk4zd40j9qs2lmne
packetprotector,npub1e7vyw7vtycrphmch5gna4yez8jhaj5ush4pyu9pd5qrwfvgpznhqsttv8r
rockstar,npub1j8y6tcdfw3q3f3h794s6un0gyc5742s0k5h5s2yqj0r70cpklqeqjavrvg
stross,npub13rrhlf0zek4n6y5f0axw4zhqpppnwnjfh5vhusq3arvnd9vtz07sjh37nr
szollo,npub100n0yahp4kan33pz3htw5e5qegs3t5umesesjp9ycz3l4xpwawws988nqc
verbiricha,npub107jk7htfv243u0x5ynn43scq9wrxtaasmrwwa8lfu2ydwag6cx2quqncxg
domain=strike.me|count=15
```

Updated error messaging looks like this (prettier error messaging - and de-clutters the main())
image
image
image

### CODE REVIEW

**Comment by snazzybytes** [comment]
Gents @rot13maxi @praveenperera in need of rust experts to review this newb rustacean 🦀 adventure.
Especially the usage of "&" borrowing, &str slices vs String etc (new to these types and the syntax so i'll take any tip)

**Comment by snazzybytes** [comment]
The only checks failing are some Linux cross compile stages? I'm ignoring it since it seems related to CI not the logic itself.

**Comment by praveenperera** [comment]
@snazzybytes Looks like this adds a dependency on openssl, maybe try rustls, or we can install it. 

Also lets avoid using `full` for features and use only the ones we need. 

This PR will make the CLI bigger, since it brings in tokio. But I suppose it could be worth it. 

If this was mine, I might put this under a cargo feature so tokio and stuff it only added for people that want it.

**Comment by snazzybytes** [comment]
> Looks like this adds a dependency on openssl, maybe try rustls, or we can install it.

How would I avoid "openssl" , switch to different HTTP (not request?) libs? Bear with me as this is my 3rd of 4th day even looking at rust 😅I added "reqwest" crate is probably where that dependency came from. 

>"we can install it"

what do you mean? where can you install it? 

>This PR will make the CLI bigger, since it brings in tokio. But I suppose it could be worth it.

NIP-05 identifiers are like the beloved feature of nostriches. It seems to be this would be useful feature for some (me lol).
The "tokio" got brought in because i wanted to make the domain fetching asynchronous (my next idea was to make the "domain fetching multithreaded" and learn the mutex etc.)

> If this was mine, I might put this under a cargo feature so tokio and stuff it only added for people that want it.

I would like to know how this works in Rust. anything i should read to make it a "cargo feature" optional for the users?
You mine like in java world with modules and optional sub-modules , except rust lang equivalent of that approach?


Thanks in advance @praveenperera

**Comment by snazzybytes** [comment]
@praveenperera thanks for mentioning the lib size also, definitely want to help... not make things worse. I compared the size of the release, i 5x-ed the lib.

```
Before:
1.0M Feb  8 15:56 key-convertr
After:
5.6M Feb  8 16:00 key-convertr
```

**Comment by praveenperera** [comment]
@snazzybytes  Forget about cargo features for now actually since this is a binary, no need to complicate it. You could probably make it a bit smaller by only using the tokio features you need instead of `full`. 

Having NIP-05 support could definitely be worth the extra 4MB. Let's let @rot13maxi decide, but I think it's definitely reasonable. 

> How would I avoid "openssl" , switch to different HTTP (not request?) libs? Bear with me as this is my 3rd of 4th day even looking at rust 😅I added "reqwest" crate is probably where that dependency came from.

OpenSSL would be a dependency for the person running the binary, most people have it. We would just need to add it to the docker file.

But for `reqwest` try the `rustls-tls` that is a pure rust implementation of SSL, and remove the dependacy on openssl being installed.

**Comment by snazzybytes** [comment]
Ahhh yes, i understand you now! First time adding "crates", don't laugh 🤣

```
tokio = { version = "1.25.0", features = ["full"] }
```

> OpenSSL would be a dependency for the person running the binary, most people have it. We would just need to add it to the docker file.

#legit

> But for reqwest try the rustls-tls that is a pure rust implementation of SSL, and remove the dependacy on openssl being installed.

Roger, I will try that

**Comment by snazzybytes** [comment]
@praveenperera what's your npub so I tag befriend you on nostr?

**Comment by praveenperera** [comment]
npub16h79qh2uy5yw7a0n8uvt4q656qhvugece9h9tw85ya4y4j20hs8q3m0xh8

**Comment by snazzybytes** [comment]
@praveenperera  I have addressed your comments with respect to dependencies - no more `openssl` in favor of rustls/rustls-tls. I have disabled all default-features and picked what's needed. Ironically the size of the release went-up further to 6.1M 😅. 

Looks like regex is taking up quite a bit - because i added "domain format string validation" to make sure the input is valid before making requests. I think the tokio async stuff and rustls/tls stuff takes up quite a bit in and of itself.

Can you take a look if this is cool and advise further?

`cargo tree` deps output:
https://gist.github.com/snazzybytes/b74fa06893e4b7c6dea2da9218e74506

---
With "Regex" (includes unicode) = 6.1M 
image
 Without regex = 5.5M
image


Also, why is this check failing,  any ideas?
https://github.com/rot13maxi/key-convertr/actions/runs/4130995448/jobs/7138233601

**Comment by praveenperera** [comment]
@snazzybytes looks like ring a dep if rustls is not supported in powerpc64le. We could probably just remove that. How many people are still using powerpc’s. 

Or if you wanted practise target specific features and fall back to just using openssl on targets that don’t support rustls

**Comment by snazzybytes** [comment]
> could probably just remov

major delay, stuff came up. back at it folks. 

oh wow, yea powerpc64le is like 2003ish. i guess direction depends on @rot13maxi vision for this tool and whether or not this powerpc64le is a hardware that will need this for NOSTR 😅 (don't know much about this hardware... but my gut feel says no )

What I will do next at least, is read about Rust a little more - and try to put existing PR changes behind a "feature" flag (learn how to break up the directory structure like Rustacean would and give option to enable/disable appropriately since it's 1MB vs 5MB 🤷‍♂️ it's a good exercise and looks like it can't hurt). I can see how it would be useful to have such `--feature nip5` , as well as other `nip11`, `nip57`, and so on. so that potential future library users will be able to enable only the `nips` they need to keep the deps lighter 💪

Let me figure out the `--features` will @rot13maxi tells us what he thinks about the `powerpc64le` part

**Pull request merged**
